// CF-03: deterministic gate between CF-02's persisted network-evidence.jsonl and the LLM
// discovery-review handoff (review-input.json). This module only loads/validates the on-disk
// index; it never extracts or populates a casino field from a response body itself — that stays
// entirely the discovery-reviewer subagent's job, cited back by artifact path (see
// .claude/agents/discovery-reviewer.md).
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import type { InteractionCandidateRecord, InteractionMode, NetworkEvidenceRecord, ReviewInputPageEvidence } from './types.ts';
import { assertPassiveOnlyInteractionRecords, PassiveInteractionContractError } from './interaction-contract.ts';

// A missing body referenced by a 'captured' record must fail the review gate explicitly — never
// continue silently with a broken evidence reference the reviewer can't actually read.
export class PostRunReviewGateError extends Error {
  readonly missingBodies: string[];

  constructor(message: string, missingBodies: string[]) {
    super(message);
    this.name = 'PostRunReviewGateError';
    this.missingBodies = missingBodies;
  }
}

export interface NetworkEvidenceGateResult {
  /** false when network-evidence.jsonl does not exist for this run — backward-compatible no-op. */
  present: boolean;
  records: NetworkEvidenceRecord[];
  capturedCount: number;
}

async function readNetworkEvidenceJsonl(indexPath: string): Promise<NetworkEvidenceRecord[]> {
  const raw = await readFile(indexPath, 'utf8');
  return raw
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line) as NetworkEvidenceRecord);
}

/**
 * Loads and validates <runDir>/network-evidence.jsonl (CF-02's index) when present.
 *
 * - Absent entirely: backward-compatible no-op (`present: false`) — a run produced before CF-02,
 *   or one with zero eligible network traffic, still assembles review-input.json normally.
 * - Present: every record with `outcome === 'captured'` must reference a `bodyPath` that actually
 *   exists on disk. Any missing body throws PostRunReviewGateError, failing the review gate for
 *   the whole run rather than silently handing the reviewer a dangling reference.
 */
export async function validateNetworkEvidenceIndex(indexPath: string): Promise<NetworkEvidenceGateResult> {
  if (!existsSync(indexPath)) {
    return { present: false, records: [], capturedCount: 0 };
  }

  const records = await readNetworkEvidenceJsonl(indexPath);
  const missingBodies: string[] = [];
  for (const record of records) {
    if (record.outcome !== 'captured') continue;
    if (!record.bodyPath || !existsSync(record.bodyPath)) {
      missingBodies.push(record.bodyPath ?? `<missing bodyPath for ${record.requestUrl}>`);
    }
  }

  if (missingBodies.length > 0) {
    throw new PostRunReviewGateError(
      `${missingBodies.length} captured network-evidence record(s) in ${indexPath} reference a missing body file: ${missingBodies.join(', ')}`,
      missingBodies,
    );
  }

  return {
    present: true,
    records,
    capturedCount: records.filter((record) => record.outcome === 'captured').length,
  };
}

// FIX-02: same style of deterministic gate as validateNetworkEvidenceIndex above, but for the
// passive/executed interaction contract. Reads <runDir>/interactions.jsonl (when present) and
// rejects the whole review gate — never silently drops or "fixes up" the offending rows — if the
// declared run interactionMode is 'passive_only' and any candidate row claims an executed-action
// outcome (revealed_evidence, state_changed_no_new_evidence, no_effect, blocked, unsafe, timeout).
// This is the second enforcement point for the same invariant crawler.ts already asserts at
// write-time — re-checked here on the read side so a legacy/local run producer that bypassed
// crawler.ts (or an interactions.jsonl edited/regenerated by hand) can never slip a false
// executed-action claim past the review pipeline.
export async function validateInteractionRecordsForReview(
  indexPath: string,
  runInteractionMode: InteractionMode,
): Promise<InteractionCandidateRecord[]> {
  if (!existsSync(indexPath)) return [];

  const raw = await readFile(indexPath, 'utf8');
  const records = raw
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line) as InteractionCandidateRecord);

  try {
    assertPassiveOnlyInteractionRecords(runInteractionMode, records);
  } catch (error) {
    if (error instanceof PassiveInteractionContractError) {
      throw new PostRunReviewGateError(
        `${indexPath} violates the passive/executed interaction contract: ${error.message}`,
        error.violatingLabels,
      );
    }
    throw error;
  }

  return records;
}

// FIX-06: the deterministic gate for review-input.json's complete per-page evidence graph
// (ReviewInputPageEvidence[]) — composes with, rather than duplicates, the two gates above:
// validateNetworkEvidenceIndex already confirmed every captured network-evidence body exists
// before its records were joined into pageEvidence, and validateInteractionRecordsForReview
// already confirmed no passive/executed contract violation exists in the interaction records
// joined into pageEvidence. This gate is the final check that every reference actually written
// into review-input.json's pageEvidence array — HTML snapshot, passive trace, and (defensively,
// re-checked here) network evidence bodies — still resolves to a real file on disk, and throws
// PostRunReviewGateError (never silently skips/drops) on the first dangling reference found.
// interactionStateRecords entries need no separate on-disk check here: they are file-less
// references built directly from validated interactions.jsonl rows, and are structurally
// restricted (by construction in review-input.ts's buildPageEvidenceGraph) to only ever contain
// an ExecutedCandidateRow (has `actionClass`) — never an ObservationCandidateRow.
export function validatePageEvidenceGraph(pageEvidence: ReviewInputPageEvidence[]): void {
  const missing: string[] = [];
  for (const page of pageEvidence) {
    if (page.htmlSnapshotPath && !existsSync(page.htmlSnapshotPath)) {
      missing.push(page.htmlSnapshotPath);
    }
    if (page.passiveTracePath && !existsSync(page.passiveTracePath)) {
      missing.push(page.passiveTracePath);
    }
    for (const record of page.networkEvidenceRecords) {
      if (record.outcome === 'captured' && (!record.bodyPath || !existsSync(record.bodyPath))) {
        missing.push(record.bodyPath ?? `<missing bodyPath for ${record.requestUrl}>`);
      }
    }
  }

  if (missing.length > 0) {
    throw new PostRunReviewGateError(
      `${missing.length} evidence reference(s) in review-input.json's pageEvidence graph point to a missing file on disk: ${missing.join(', ')}`,
      missing,
    );
  }
}
