// Shared contracts for the url-map-recon pipeline (ADR-001).
//
// Core invariant: everything the LLM recon agent produces or consumes here is
// URL-shaped data (absolute URLs, route paths, source ids, counts, booleans,
// statuses, errors) — never DOM text, textContent/innerText, alt/title text,
// JSON bodies, script bodies, or product names. See README-codebase / ADR-001.

export const SOURCE_FAMILIES = [
  'dom_url_attributes',
  'document_metadata',
  'frame_form',
  'network_request',
  'performance_resource',
  'inline_script',
  'same_origin_script',
  'json_endpoint',
  'framework_manifest',
  'robots_sitemap',
  'sitemap_index',
  'spa_route',
  'locale_variant',
  'menu_injected',
] as const;

export type SourceFamily = (typeof SOURCE_FAMILIES)[number];

export const COVERAGE_STATUSES = ['present', 'absent', 'blocked', 'unsupported', 'error'] as const;
export type CoverageStatus = (typeof COVERAGE_STATUSES)[number];

/** {output_dir}/url-source-coverage.json — one entry per source family, always. */
export type SourceCoverageEntry = { sourceFamily: SourceFamily; status: CoverageStatus; note?: string; count?: number };
export type SourceCoverage = SourceCoverageEntry[];

export function emptyCoverage(): SourceCoverage {
  return SOURCE_FAMILIES.map((sourceFamily) => ({ sourceFamily, status: 'unsupported' as CoverageStatus }));
}

// --- Entry / origin contract (document-url-map.json entries) -------------

export const ENTRY_SOURCES = [
  'dom_anchor',
  'config_route',
  'bundle_footer',
  'bundle_seo',
  'bundle_other',
  'external',
  'robots_sitemap',
  'sitemap_index',
  'performance_resource',
  'network_request',
  'framework_manifest',
  'spa_route',
  'document_metadata',
  'frame_form',
  'inline_script',
  'same_origin_script',
  'menu_injected',
] as const;
export type EntrySource = (typeof ENTRY_SOURCES)[number];

export const ORIGIN_STATUSES = ['official_same_origin', 'external_approved'] as const;
export type OriginStatus = (typeof ORIGIN_STATUSES)[number];

export type LabelSource = 'url_slug';

export type UrlMapEntry = {
  canonicalUrl: string;
  url_id?: string; // Stable identifier for this URL in relevance matrix (issue 10, generated by classifier)
  derivedLabel?: string;
  labelSource?: LabelSource;
  originStatus: OriginStatus;
  source: EntrySource;
  // URL metadata classification (issue 08)
  routeTokens?: string[];
  slugLabel?: string;
  pageClass?: string;
  isMandatory?: boolean;
  isProductCategoryLanding?: boolean;
  sourceConfidence?: number;
  redirectStatus?: string;
};

// Note: template-category classification (mapping URLs to research-template
// categories) is explicitly out of scope for this session — do not add a
// `classifications` field or a classification module here.

// --- Declarative extraction recipe (extraction-recipe.json) --------------

export const EXTRACTOR_IDS = [
  'DOM_URL_ATTRIBUTES_V1',
  'DOCUMENT_METADATA_URLS_V1',
  'FRAME_FORM_URLS_V1',
  'NETWORK_REQUEST_URLS_V1',
  'PERFORMANCE_RESOURCE_URLS_V1',
  'INLINE_SCRIPT_URL_TOKENS_V1',
  'SAME_ORIGIN_SCRIPT_URL_TOKENS_V1',
  'JSON_ENDPOINT_URL_TOKENS_V1',
  'FRAMEWORK_MANIFEST_URL_TOKENS_V1',
  'ROBOTS_SITEMAP_URLS_V1',
  'SITEMAP_URLS_V1',
  'SPA_ROUTE_URL_TOKENS_V1',
  'INTERACTION_NAVIGATION_URLS_V1',
] as const;
export type ExtractorId = (typeof EXTRACTOR_IDS)[number];

/**
 * Fixed home for every registered URL extractor: the `EntrySource` its recorded
 * observations are dispatched under, which in turn drives its `SourceFamily`
 * coverage bucket (see `extraction-coordinator.ts`'s `mapSourceToFamily`). Every
 * id in `EXTRACTOR_IDS` must have an entry here — the stage-dispatcher's
 * observation-driven recipe builder (Issue 27) looks up this map for every
 * unique extractor id it finds recorded in `page-observations.jsonl`.
 */
export const EXTRACTOR_ENTRY_SOURCE: Record<ExtractorId, EntrySource> = {
  DOM_URL_ATTRIBUTES_V1: 'dom_anchor',
  DOCUMENT_METADATA_URLS_V1: 'document_metadata',
  FRAME_FORM_URLS_V1: 'frame_form',
  NETWORK_REQUEST_URLS_V1: 'network_request',
  PERFORMANCE_RESOURCE_URLS_V1: 'performance_resource',
  INLINE_SCRIPT_URL_TOKENS_V1: 'inline_script',
  SAME_ORIGIN_SCRIPT_URL_TOKENS_V1: 'same_origin_script',
  JSON_ENDPOINT_URL_TOKENS_V1: 'config_route',
  FRAMEWORK_MANIFEST_URL_TOKENS_V1: 'framework_manifest',
  ROBOTS_SITEMAP_URLS_V1: 'robots_sitemap',
  SITEMAP_URLS_V1: 'sitemap_index',
  SPA_ROUTE_URL_TOKENS_V1: 'spa_route',
  INTERACTION_NAVIGATION_URLS_V1: 'menu_injected',
};

// Behavior/interaction/product observation kinds (Issue 24) — distinct from
// `ExtractorId` (the URL-extractor registry every id in `EXTRACTOR_IDS` must have a
// matching implementation for, see extractors.ts). A browser agent records these into
// page-observations.jsonl; the corresponding deterministic provider
// (observation-provider.ts) parses `content` back into the structured shape
// (SectionBehavior / InteractionRecord / product items) that the existing stage
// 8/9/12 seams already accept. The agent never writes the canonical
// page-behavior.json / interaction-records.json / product-candidates.json itself.
export const OBSERVATION_KINDS = [
  'PAGE_BEHAVIOR_OBSERVATION_V1',
  'INTERACTION_OBSERVATION_V1',
  'PRODUCT_OBSERVATION_V1',
] as const;
export type ObservationKind = (typeof OBSERVATION_KINDS)[number];

export type RecipeStepV1 = {
  extractorId: ExtractorId;
  pageUrl: string;
  source: EntrySource;
  params?: Record<string, unknown>;
  resultType: 'url_list';
  /**
   * The raw input kind (see `ExtractorInputKind`, declared below) this step's
   * observation carried when the recipe was recorded. Optional for backward
   * compatibility with recipes recorded before this field existed — those are
   * always treated as compatible (Issue 31 only guards recipes that recorded
   * a mode). Compared against the extractor's *current*
   * `EXTRACTOR_ACCEPTED_INPUT_TYPES` at replay time; a stored recipe can go
   * stale if the extractor's contract changes after it was recorded.
   */
  recordedInputMode?: ExtractorInputKind;
};

export type RecipeV1 = {
  version: 1;
  casinoId: string;
  recordedAt: string;
  steps: RecipeStepV1[];
};

// --- Extractor input/output ------------------------------------------------
//
// Extractors are pure TS functions. In production they run inside the page via
// browser_evaluate; offline/in-repo they take an already-supplied text/array
// snapshot. The return type structurally cannot carry the raw input back out —
// only `urls`, `status`, and `error`.

export type ExtractorInput = {
  pageUrl: string;
  params?: Record<string, unknown>;
  /** raw HTML snapshot supplied by the caller (never echoed back) */
  html?: string;
  /** script bodies supplied by the caller (never echoed back) */
  scripts?: string[];
  /** JSON/config text supplied by the caller (never echoed back) */
  json?: string;
  /** plain text supplied by the caller, e.g. robots.txt / sitemap.xml body */
  text?: string;
  /** pre-resolved candidate URL/path strings (e.g. Performance API entries, or any observation recorded with content_type "candidates") */
  candidates?: string[];
  /** id of the PageObservation this input was built from, when it came from one (Issue 29 provenance) */
  observationId?: string;
  /**
   * Recorded-fixture signal that this step's source could not be reached as
   * a source (not merely "reached and found zero"): `absent` when the
   * resource itself doesn't exist (e.g. sitemap.xml 404), `blocked` when an
   * auth gate stopped access before extraction could run.
   */
  sourceStatus?: 'absent' | 'blocked';
};

export type ExtractorStatus = 'ok' | 'empty' | 'error';

export type ExtractorResult = {
  status: ExtractorStatus;
  urls: string[];
  rejectedCount: number;
  error?: string;
};

export type ExtractorFn = (input: ExtractorInput) => ExtractorResult;

// --- Extractor input contracts (Issue 29) -----------------------------------
//
// Splits extractor *input* (what raw shape a source-specific parser is willing to
// parse) from extractor *output* (the URLs it produces). A `candidates` observation
// is already-extracted output — it never counts as one of these raw input kinds and
// never reaches a source-specific parser; see `ingestCandidates` in
// extraction-coordinator.ts.
export const EXTRACTOR_INPUT_KINDS = ['html', 'json', 'text', 'scripts'] as const;
export type ExtractorInputKind = (typeof EXTRACTOR_INPUT_KINDS)[number];

/**
 * Every registered extractor id's accepted raw input kind(s). Consulted by the
 * candidate-ingestion/source-parser split in extraction-coordinator.ts; extractors
 * whose observations only ever carry pre-resolved candidates (Performance API,
 * network requests) declare an empty list — they never receive raw content.
 */
export const EXTRACTOR_ACCEPTED_INPUT_TYPES: Record<ExtractorId, ExtractorInputKind[]> = {
  DOM_URL_ATTRIBUTES_V1: ['html'],
  DOCUMENT_METADATA_URLS_V1: ['html'],
  FRAME_FORM_URLS_V1: ['html'],
  NETWORK_REQUEST_URLS_V1: [],
  PERFORMANCE_RESOURCE_URLS_V1: [],
  INLINE_SCRIPT_URL_TOKENS_V1: ['scripts'],
  SAME_ORIGIN_SCRIPT_URL_TOKENS_V1: ['scripts'],
  JSON_ENDPOINT_URL_TOKENS_V1: ['json'],
  FRAMEWORK_MANIFEST_URL_TOKENS_V1: ['json'],
  ROBOTS_SITEMAP_URLS_V1: ['text'],
  SITEMAP_URLS_V1: ['text'],
  SPA_ROUTE_URL_TOKENS_V1: ['scripts'],
  INTERACTION_NAVIGATION_URLS_V1: ['html'],
};

/**
 * One accepted candidate as it lands in raw-url-candidates.json (Issue 29). Carries
 * provenance (which extractor id discovered it, from which source family, and from
 * which recorded observation) all the way to Stage 3 output, before URL cleaning.
 */
export type RawUrlCandidate = {
  url: string;
  sourceFamily: SourceFamily;
  extractorId: ExtractorId;
  observationId?: string;
};

/**
 * Typed failure for dispatching a raw-source observation (html/json/text/scripts)
 * into an extractor that does not declare that input kind in
 * `EXTRACTOR_ACCEPTED_INPUT_TYPES`. Never converted into an empty successful result.
 */
export type ExtractorInputContractMismatch = {
  code: 'EXTRACTOR_INPUT_CONTRACT_MISMATCH';
  extractorId: ExtractorId;
  observationId?: string;
  expectedInputTypes: ExtractorInputKind[];
  receivedInputType: ExtractorInputKind;
  sourceFamily: SourceFamily;
};

// --- Product collection -----------------------------------------------------

export type ProductSection = 'sports' | 'live-casino' | 'slots';

export type ProductEntry = { title: string; url: string | null };

export type ProductSectionResult =
  | { section: ProductSection; items: ProductEntry[] }
  | { section: ProductSection; status: 'human_required' | 'blocked' | 'absent'; reason: string };

// --- Page behavior profiling -----------------------------------------------

export const BEHAVIOR_SECTIONS = ['landing', 'sports', 'live-casino', 'slots', 'cashier', 'promotions'] as const;
export type BehaviorSection = (typeof BEHAVIOR_SECTIONS)[number];

export type GateType = 'age_verification' | 'cookie_consent' | 'geo_block' | 'login_required' | 'marketing_popup';
export type GateTrigger = 'immediate' | 'after_age_gate' | 'after_cookie_gate' | 'on_interaction' | 'on_scroll';

export type Gate = {
  type: GateType;
  trigger: GateTrigger;
  dismiss: string; // CSS selector or interaction path
};

export type RenderingType = 'static_html' | 'js_loaded' | 'modal' | 'partial_dynamic';
export type LoadIndicator = 'spinner' | 'skeleton' | 'placeholder' | 'none';
export type ContentStructure = 'list' | 'grid' | 'tabs' | 'accordion' | 'carousel' | 'custom';
export type CollectionType = 'static_list' | 'pagination' | 'load_more' | 'infinite_scroll' | 'per_click' | 'unknown';

export type InteractiveElement = {
  type: 'tab' | 'dropdown' | 'filter' | 'accordion' | 'sort' | 'pagination' | 'load_more' | 'button';
  selector: string;
  effect: string;
  count?: number; // for tabs, dropdowns, etc.
};

export type Collection = {
  type: CollectionType;
  visible_count: number;
  total_count?: number; // if indicated on page
};

export type SectionBehavior = {
  nav_path?: string[]; // click paths to navigate to this section
  url: string;
  rendering: RenderingType;
  load_indicator?: LoadIndicator;
  content_structure: ContentStructure;
  interactive_elements?: InteractiveElement[];
  collection: Collection;
  collector_items?: number; // counts from deterministic product collector
  notes?: string;
};

export type BehaviorSectionResult =
  | SectionBehavior
  | { status: 'human_required' | 'blocked' | 'absent'; reason: string };

export type PageBehaviorProfile = {
  casino_id: string;
  geo: string;
  locale: string;
  profiled_at: string;
  landing?: {
    url: string;
    gates?: Gate[];
  };
  sections?: Partial<Record<BehaviorSection, BehaviorSectionResult>>;
};

// --- Browser agent observation contract (Issue 24) -------------------------
//
// When browser agents observe the live site, they write structured observations
// to the run directory. These observations are interchangeable with fixture data —
// deterministic stages read through an InputProvider seam and cannot distinguish
// between observations and recorded fixtures.

export const OBSERVATION_STATUSES = ['present', 'absent', 'blocked', 'error'] as const;
export type ObservationStatus = (typeof OBSERVATION_STATUSES)[number];

export const OBSERVATION_CONTENT_TYPES = ['html', 'scripts', 'json', 'text', 'candidates'] as const;
export type ObservationContentType = (typeof OBSERVATION_CONTENT_TYPES)[number];

/**
 * A page observation written by a browser agent to the run directory.
 * Captures what a page source yielded, with explicit status for unobtainable sources.
 * Never omits observations, never fabricates content, never executes instruction-like text.
 */
export type PageObservation = {
  /** Unique identifier for this observation */
  observation_id: string;
  /** Which extractor (URL discovery) or observation kind (behavior/interaction/product) this observation is for */
  extractor_id: ExtractorId | ObservationKind;
  /** The page URL that was observed */
  page_url: string;
  /** Whether content was obtainable */
  status: ObservationStatus;
  /** Type of content (html, scripts, json, text, or pre-resolved candidates) */
  content_type: ObservationContentType;
  /** The content itself (only present if status is 'present') */
  content?: string | string[];
  /** Reason if blocked or error (e.g., 'login_required', 'geo_block', 'network_error') */
  reason?: string;
  /** When this observation was recorded */
  timestamp: string;
};

/**
 * Metadata tracking which provider was used for a run's observations.
 * Allows runs to declare whether they used recorded fixtures or live observations.
 */
export type ObservationProviderMetadata = {
  provider_type: 'fixture_recorded' | 'live_browser';
  provider_name?: string;
  observations_path?: string;
};

